package controller;

import datos.BaseDatos;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;
import load.LoadMenuEntView;

public class AddEntViewController {
	@FXML
    private Button BtnBack;

    @FXML
    private Button BtnCrear;
    
    @FXML
    private Label TxtError;

    @FXML
    private TextField TxtFecha;

    @FXML
    private TextField TxtTel;

    @FXML
    private AnchorPane Vista;

    @FXML
    private TextField txtCed;

    @FXML
    private TextField txtNom;

	private BaseDatos dataprovider = new BaseDatos();
	
	private LoadMenuEntView lmvv;
	/**
     * Método llamado cuando se hace clic en el botón de retroceso.
     * Crea una nueva instancia de LoadMenuEntView para cargar la vista del menú de entrenador.
     * 
     * @param event El evento de clic del mouse.
     */
	public void onBackClicked(MouseEvent event) {
		// TODO Autogenerated
		lmvv = new LoadMenuEntView((Stage)this.BtnBack.getScene().getWindow());
	}
	

	/**
     * Método llamado cuando se hace clic en el botón de crear.
     * Obtiene los datos del nuevo entrenador de los campos de texto y llama al método guardarEnt del proveedor de datos.
     * Muestra un mensaje de éxito o error en la etiqueta TxtError.
     * 
     * @param event El evento de clic del mouse.
     */
	@FXML
	void onCrearClicked(MouseEvent event) {
		String cedula = txtCed.getText();
		String nombre = txtNom.getText();
		String telefono = TxtTel.getText();
		String fecha = TxtFecha.getText();
		boolean exito = dataprovider.guardarEnt(cedula, nombre, telefono, fecha);
        if (exito) {
        	TxtError.setText("Completado");
        } 
        else {
        	TxtError.setText("Error en guardar");
        }
	}
}
