package controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;
import load.LoadAddProdView;
import load.LoadAddVentasView;
import load.LoadBusVentaView;
import load.LoadEditVentasView;
import load.LoadMenuVentaView;
import load.LoadTendVentaView;
import load.LoadUsuarioView;

public class MenuVentaViewController {
	@FXML
	private Button BtnBack;
	@FXML
	private Button BtnAdd;
	@FXML
	private Button BtnEdit;
	@FXML
	private Button BtnBus;
	@FXML
	private Button BtnTen;
	@FXML
	private Button BtnAddProd;
	
	
	private LoadAddVentasView lav;
	
	private LoadAddProdView lpv;
	
	private LoadBusVentaView lbv;
	
	private LoadEditVentasView lev;
	
	private LoadTendVentaView ltv;
	
	private LoadUsuarioView lu;

	/**
	 * Método llamado cuando se hace clic en el botón de retroceso.
	 * Carga la vista de usuario correspondiente.
	 *
	 * @param event El evento de clic del mouse.
	 */
	@FXML
	public void onBackClicked(MouseEvent event) {
		// TODO Autogenerated
		lu = new LoadUsuarioView((Stage)this.BtnBack.getScene().getWindow());
	}
	/**
	 * Método llamado cuando se hace clic en el botón de agregar.
	 * Carga la vista de agregar ventas correspondiente.
	 *
	 * @param event El evento de clic del mouse.
	 */
	@FXML
	public void onAddClicked(MouseEvent event) {
		// TODO Autogenerated
		lav = new LoadAddVentasView((Stage)this.BtnAdd.getScene().getWindow());
	}
	/**
	 * Método llamado cuando se hace clic en el botón de editar.
	 * Carga la vista de editar ventas correspondiente.
	 *
	 * @param event El evento de clic del mouse.
	 */
	@FXML
	public void onEditClicked(MouseEvent event) {
		// TODO Autogenerated
		lev = new LoadEditVentasView((Stage)this.BtnEdit.getScene().getWindow());
	}
	/**
	 * Método llamado cuando se hace clic en el botón de búsqueda.
	 * Carga la vista de búsqueda de ventas correspondiente.
	 *
	 * @param event El evento de clic del mouse.
	 */
	@FXML
	public void onBusClicked(MouseEvent event) {
		// TODO Autogenerated
		lbv = new LoadBusVentaView((Stage)this.BtnBus.getScene().getWindow());
	}
	/**
	 * Método llamado cuando se hace clic en el botón de tender.
	 * Carga la vista de tender ventas correspondiente.
	 *
	 * @param event El evento de clic del mouse.
	 */
	@FXML
	public void onTenClicked(MouseEvent event) {
		// TODO Autogenerated
		ltv = new LoadTendVentaView((Stage)this.BtnTen.getScene().getWindow());
	}
	/**
	 * Método llamado cuando se hace clic en el botón de agregar producto.
	 * Carga la vista de agregar producto correspondiente.
	 *
	 * @param event El evento de clic del mouse.
	 */
	@FXML
	public void onAddProdClicked(MouseEvent event) {
		// TODO Autogenerated
		lpv = new LoadAddProdView((Stage)this.BtnAddProd.getScene().getWindow());
	}
}
