package controller;

import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.input.MouseEvent;
import javafx.stage.Stage;
import load.LoadAddEntView;
import load.LoadAddSerView;
import load.LoadBusSerView;
import load.LoadEditSerView;
import load.LoadTendSerView;
import load.LoadUsuarioView;

public class MenuEntViewController {
	@FXML
	private Button BtnBack;
	@FXML
	private Button BtnAdd;
	@FXML
	private Button BtnEdit;
	@FXML
	private Button BtnBus;
	@FXML
	private Button BtnTen;
	@FXML
	private Button BtnAddProd;
	
	
	private LoadAddSerView lar;
	
	private LoadAddEntView lpr;
	
	private LoadBusSerView lbr;
	
	private LoadEditSerView ler;
	
	private LoadTendSerView ltr;
	
	private LoadUsuarioView lu;

	/**
	 * Método llamado cuando se hace clic en el botón de retroceso.
	 * Carga la vista de usuario correspondiente.
	 *
	 * @param event El evento de clic del mouse.
	 */
	@FXML
	public void onBackClicked(MouseEvent event) {
		// TODO Autogenerated
		lu = new LoadUsuarioView((Stage)this.BtnBack.getScene().getWindow());
	}
	/**
	 * Método llamado cuando se hace clic en el botón de agregar.
	 * Carga la vista de agregar servicio correspondiente.
	 *
	 * @param event El evento de clic del mouse.
	 */
	@FXML
	public void onAddClicked(MouseEvent event) {
		// TODO Autogenerated
		lar = new LoadAddSerView((Stage)this.BtnAdd.getScene().getWindow());
	}
	/**
	 * Método llamado cuando se hace clic en el botón de editar.
	 * Carga la vista de editar servicio correspondiente.
	 *
	 * @param event El evento de clic del mouse.
	 */
	@FXML
	public void onEditClicked(MouseEvent event) {
		// TODO Autogenerated
		ler = new LoadEditSerView((Stage)this.BtnEdit.getScene().getWindow());
	}
	/**
	 * Método llamado cuando se hace clic en el botón de búsqueda.
	 * Carga la vista de búsqueda de servicio correspondiente.
	 *
	 * @param event El evento de clic del mouse.
	 */
	@FXML
	public void onBusClicked(MouseEvent event) {
		// TODO Autogenerated
		lbr = new LoadBusSerView((Stage)this.BtnBus.getScene().getWindow());
	}
	/**
	 * Método llamado cuando se hace clic en el botón de tender.
	 * Carga la vista de tender servicio correspondiente.
	 *
	 * @param event El evento de clic del mouse.
	 */
	@FXML
	public void onTenClicked(MouseEvent event) {
		// TODO Autogenerated
		ltr = new LoadTendSerView((Stage)this.BtnTen.getScene().getWindow());
	}
	/**
	 * Método llamado cuando se hace clic en el botón de agregar entrenador.
	 * Carga la vista de agregar entrenador correspondiente.
	 *
	 * @param event El evento de clic del mouse.
	 */
	@FXML
	public void onAddEntClicked(MouseEvent event) {
		// TODO Autogenerated
		lpr = new LoadAddEntView((Stage)this.BtnAddProd.getScene().getWindow());
	}
}
