package controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;
import load.LoadMenuEntView;
import load.LoadMenuVentaView;
import javafx.scene.input.MouseEvent;

public class TendSerVistaController {
	@FXML
	private AnchorPane Vista;
	@FXML
	private Button BtnBack;
	

	// Event Listener on Button[#BtnBack].onMouseClicked
	@FXML
	public void onBackClicked(MouseEvent event) {
		// TODO Autogenerated
		new LoadMenuEntView((Stage)this.BtnBack.getScene().getWindow());
	}
}
