package controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;
import load.LoadMenuVentaView;
import javafx.scene.input.MouseEvent;

public class TendVentaViewController {
	@FXML
	private AnchorPane Vista;
	@FXML
	private Button BtnBack;
	
	private LoadMenuVentaView lmvv;

	// Event Listener on Button[#BtnBack].onMouseClicked
	@FXML
	public void onBackClicked(MouseEvent event) {
		// TODO Autogenerated
		lmvv = new LoadMenuVentaView((Stage)this.BtnBack.getScene().getWindow());
	}
}
