package controller;

import java.util.Map;

import datos.BaseDatos;
import javafx.fxml.FXML;
import javafx.scene.chart.BarChart;
import javafx.scene.chart.XYChart;
import javafx.scene.control.Button;

import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;
import load.LoadMenuVentaView;
import javafx.scene.input.MouseEvent;

public class TendVentaViewController {
	@FXML
	private AnchorPane Vista;
	@FXML
    private BarChart<String, Number> barChart;
    @FXML
    private Button BtnBack;

    private BaseDatos baseDatos;

    public void initialize() {
        baseDatos = new BaseDatos();
        cargarDatos();
    }

    private void cargarDatos() {
        Map<String, Integer> productosMasVendidos = baseDatos.getProductosMasVendidos();
        XYChart.Series<String, Number> series = new XYChart.Series<>();

        for (Map.Entry<String, Integer> entry : productosMasVendidos.entrySet()) {
            series.getData().add(new XYChart.Data<>(entry.getKey(), entry.getValue()));
        }

        barChart.getData().add(series);
    }
	
	private LoadMenuVentaView lmvv;

	// Event Listener on Button[#BtnBack].onMouseClicked
	@FXML
	public void onBackClicked(MouseEvent event) {
		// TODO Autogenerated
		lmvv = new LoadMenuVentaView((Stage)this.BtnBack.getScene().getWindow());
	}
}
